### ISSUE TITLE
Package installation order

### ISSUE THREAD

**Issue by alexwhitman** [skx/marionette#110]
Package installation could result in unexpected packages being installed depending on the order of installation. Take [php7.4](https://packages.debian.org/bullseye/php7.4) for example. The package depends on libapache2-mod-php7.4 OR php7.4-fpm OR php7.4-cgi.

If a `package` definition of the below is used:
```
package {
    name => "php",
    package => [ "php7.4", "php7.4-fpm" ],
    state => "installed"
}
```
will effectively result in
```
apt-get install php7.4
apt-get install php7.4-fpm
```
with the issue being that the first command will also install libapache2-mod-php7.4. This is different to running `apt-get install php7.4 php7.4-fpm` as the dependency resolution will know that the package requirements are met without having to pick additional packages.

This can be resolved by a user by changing the order of the packages in the defintion to `package => [ "php7.4-fpm", "php7.4" ]`.

The easy fix is to document this. The alternative is to change the `package` module to install all required packages in a single command.

**Comment by skx** [comment]
> The alternative is to change the package module to install all required packages in a single command.

That seems like an easy win, I'd be happy to make that change.

(Sorry somehow missed this notification, or it went out of my mind just after I'd read it!)
