### ISSUE TITLE
how do I install a specific version?

### ISSUE THREAD

**Issue by httpete** [skx/marionette#121]
This is what I do now:
go install github.com/skx/marionette@master

But I want to pin it to 0.18.0 . Your doc doesn't show that.

**Comment by skx** [comment]
This is more of a `go` question, but you should find this works:

```
go install github.com/skx/marionette@v0.18.0
```

**Comment by httpete** [comment]
Thank you @skx . I am learning go through using your product. Thanks. It is really working great now. You should share / sell the idea of http://asdf-vm.com/ in concert with marionette. Those two tools together can really provision a dev env nicely.
