### ISSUE TITLE
add the ability to use sudo/doas when installing package, modifying user/group,...

### ISSUE THREAD

**Issue by tannevaled** [skx/marionette#123]
Hi,

for shell blocks we can prefix the command with sudo/doas.
presently it seems not possible to run marionette from a regular user and install package/modify user-group.

it would be a great addition.

**Comment by skx** [comment]
That's a good observation, I'd need to work out the best approach.  Perhaps an `elevate => "sudo"` setting, or similar, for those operations?

To be honest such a parameter would probably make sense for _all_ operations.  As even making directories, or changing permissions of files could potentially be privileged operations.

**Comment by skx** [comment]
I'll take care of this over the weekend, looks like it will be an easy thing to add to  package/user/group modules, but harder for other things.
