### ISSUE TITLE
prompt for user input?

### ISSUE THREAD

**Issue by httpete** [skx/marionette#88]
IS there any way to execute a prompt or even `read varname` ?

**Comment by skx** [comment]
There is currently no way to prompt the user for input, however reading from environmental variables will work.

Something like:

```
log{
 message => "echo ${FOO}"
}
```

Will read the environmental variable `FOO` if there is not a variable with that name already:

```
frodo ~/Repos/github.com/skx/marionette $ FOO=xxx ./marionette log.in 
2022/02/10 06:10:25 [USER] echo xxx
```
