### ISSUE TITLE
contains doesn't work on cat'd file

### ISSUE THREAD

**Issue by httpete** [skx/marionette#90]
```let mysqlcnf = `cat ${HOME}/.my.cnf`

shell { name    => "Adding datadir, adding new",
        command => "sh edit_mysql.sh", 
        unless => contains($mysqlcnf, 'Required')
}

The file is there, contains the string Required, and it doesn't work as it should.

**Comment by skx** [comment]
That's an odd one, as my own simple test succeeded as I expected:

```
let content = `cat /etc/passwd`

log {
      message => "root is not present present",
      unless => contains("$content", "root")
}

log {
       message => "${content}"
}
```

Are you running under `sudo` or something else that would mess up "${HOME}" ?  If not I'd suggest adding a logging line or two:

```
log {   message => "Content: ${mysqlcnf}" }
```

And taking it from there.

**Comment by alexwhitman** [comment]
Are you setting `${HOME}` yourself as the built in variable is `${HOMEDIR}`?

**Comment by skx** [comment]
Could never reproduce this, closing on that basis.
